# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e63a63ce0a26c52d5f60bf121c58b93f7f95ebcfb9688987c737c98a1b3079fcc95ea066b24fa519e74a0a3fca754b0bb3d6c5b387ddeac414992792897b3e8
  scraper_url: http://localhost:5200/populate

test:
  secret_key_base: 882b8fd7d74f10f51698fab50475df96a4ee1d47ad2520c1b05fd3439f728f3e9cf82833df27945f3efd5fc348518639465434813bf25e1cfeddce5f734e615c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  scraper_url: https://evening-badlands-71821.herokuapp.com/populate
